# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'recycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'Firebase/Core' 
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionLabelModel'
  
  # This is the pod responsible for barcode scanning
  pod 'Firebase/MLVisionBarcodeModel'

  target 'recycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recycleUITests' do
    # Pods for testing
  end

end
